export const NICHE_OPTIONS = [
  'MOBILIDADE ELÉTRICA',
  'TECNOLOGIA E SISTEMAS',
  'SERVIÇOS ESPECIALIZADOS',
  'INDÚSTRIA E SUPRIMENTOS',
  'VAREJO E E-COMMERCE',
  'INDÚSTRIA E ENGENHARIA',
  'SAÚDE E BEM-ESTAR',
  'ALIMENTOS E BEBIDAS',
  'INDÚSTRIA E NÁUTICA',
  'TECNOLOGIA E SEGURANÇA',
  'INDÚSTRIA E LOGÍSTICA',
  'EDUCAÇÃO E DESENVOLVIMENTO',
  'SERVIÇOS FINANCEIROS',
] as const;

export type NicheOption = (typeof NICHE_OPTIONS)[number];
