// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

declare global {
  interface Window {
    __ENV__?: {
      VITE_SUPABASE_URL?: string;
      VITE_SUPABASE_PUBLISHABLE_KEY?: string;
      VITE_SUPABASE_PROJECT_ID?: string;
    };
  }
}

// Runtime (Easypanel): window.__ENV__ injetado por config.js | Build: import.meta.env
const SUPABASE_URL =
  (typeof window !== 'undefined' && window.__ENV__?.VITE_SUPABASE_URL) ||
  import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  (typeof window !== 'undefined' && window.__ENV__?.VITE_SUPABASE_PUBLISHABLE_KEY) ||
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const isDev = import.meta.env.DEV;
const missingEnv = !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY;

if (missingEnv) {
  const msg =
    'Supabase não configurado. Defina VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY (copie .env.example para .env).';
  if (isDev) {
    console.warn(msg);
  } else {
    console.error(msg);
    throw new Error(msg);
  }
}

// Em dev sem .env: usa placeholders para a app carregar (login falhará até configurar)
const effectiveUrl = missingEnv && isDev ? 'https://placeholder.supabase.co' : SUPABASE_URL!;
const effectiveKey = missingEnv && isDev ? 'placeholder-anon-key' : SUPABASE_PUBLISHABLE_KEY!;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(effectiveUrl, effectiveKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Isola a sessão do app — evita colisão com outros projetos Supabase
    // no mesmo domínio e sobrevive a mudanças de subdomínio.
    storageKey: 'mgrowth-auth',
    // PKCE é o fluxo recomendado para SPAs em 2025 (mais seguro que o
    // implicit flow default e suporta refresh tokens confiáveis).
    flowType: 'pkce',
    // Permite capturar callbacks OAuth/magic link sem lógica custom.
    detectSessionInUrl: true,
  }
});